biddr_api/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  # config/routes.rb
  resource :sessions, only: [:new, :destroy, :create]

  resources :auctions do
    resources :bids, only: [:show, :create]
  end

  # resources :answers, only: [:show, :create]

  root 'auctions#home'

  # # index
  # get '/auctions' => 'auctions#index', as: :auctions


  # # new
  # get '/auctions/new' => 'auctions#new', as: :new_auction
  # post '/auctions' => 'auctions#create'

  # post '/auctions/:auction_id/bids' => 'bids#create'
  # get '/auctions/:auction_id/bids/:id' => 'bids#show'
  

  # # show
  # get '/auctions/:id' => 'auctions#show', as: :auction

  # # delete
end

biddr_api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

biddr_api/app/models/auction.rb
class Auction < ApplicationRecord
    has_many :bids
end

biddr_api/app/models/bid.rb
class Bid < ApplicationRecord
    belongs_to :auction

    validates :bid, presence: true
end

biddr_api/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

biddr_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        redirect_to new_sessions_path, notice: "Please sign in" unless user_signed_in?
      end
    
      def user_signed_in?
        current_user.present?
      end
      helper_method :user_signed_in?
    
      def current_user
        @current_user ||= User.find_by_id session[:user_id]
      end
      helper_method :current_user
end

biddr_api/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
    before_action :authenticate_user!, except: [:show]

    def home
    end

    def index
        @auctions = Auction.all.order(created_at: :desc)
    end

    def show
        @auction = Auction.find(params[:id])
        @bid = Bid.new
    end

    def new
        @new_auction = Auction.new
    end

    def create
        @new_auction = Auction.new params.require(:auction).permit(:title, :description, :ends_at, :reserve_price)
        if @new_auction.save
            redirect_to auctions_path
        else
            redirect_to new_auction_path
        end
    end
end

biddr_api/app/controllers/bids_controller.rb
class BidsController < ApplicationController
    def create
       @auction = Auction.find params[:auction_id]
       bid_params = params.require(:bid).permit(:bid)
       @bid = Bid.new bid_params
       if @bid.save
            redirect_to auction_path(@auction)
       else
        render '/auctions/show'
       end
    end
end

biddr_api/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      @user = User.find_by_email params[:email]
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Logged in"
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
    end
  
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
    end
  end
  

biddr_api/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Logged In!"
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation
      )
    end
  end
  

biddr_api/app/helpers/application_helper.rb
module ApplicationHelper
end

biddr_api/app/helpers/auctions_helper.rb
module AuctionsHelper
end

biddr_api/app/helpers/bids_helper.rb
module BidsHelper
end

biddr_api/app/helpers/sessions_helper.rb
module SessionsHelper
end

biddr_api/app/helpers/users_helper.rb
module UsersHelper
end

biddr_api/app/views/auctions/home.html.erb
<%= image_tag('biddr-background-image.jpg', width: '100%', height: '100%') %>

biddr_api/app/views/auctions/index.html.erb
<h1 style="text-align: center; background-color: #F5F5DC;">AUCTIONS</h1>
<span style="padding: 10px;"><%= link_to "Create Auction", new_auction_path, :class => "btn btn-secondary" %></span> <br> <br>

<div style="margin-left: 10px;">
    <%= @auctions.each do |auction| %>
        <h2>
            <%= link_to auction.title, auction_path(auction) %>
        </h2>
        <h4>Posted on <%= auction.created_at %>
        </h4>

        <hr>
        <% end %>
</div>

biddr_api/app/views/auctions/new.html.erb
<h1 style="text-align: center; background-color: #F5F5DC;">CREATE AN AUCTION</h1>

<div class="new-auction-div">
<%= form_for(@new_auction) do |a| %>
<%= a.label "Title*" %> <br>
<%= a.text_field :title %> <br> <br>
<%= a.label "Description*" %> <br>
<%= a.text_area :description %> <br> <br>
<%= a.label "Ends at*" %> <br>
<%= a.text_field :ends_at %> <br> <br>
<%= a.label "Reserve Price*" %> <br>
<%= a.text_field :reserve_price%> <br> <br>
<%= a.submit "Save", :class => "btn btn-secondary" %>
<% end %>
</div>

biddr_api/app/views/auctions/show.html.erb
<div class="big-show-div">
  <div class="show-div">
    <h3>
      <%= @auction.title %>
    </h3>
    <p>
      <%= @auction.description %>
    </p>

    <%= form_for :bid do |f| %>
      <%= f.text_field :bid, :placeholder=> "Enter bid amount here...$$$" %> <br> <br>
        <%= f.submit "Bid" , :class=> "btn btn-secondary"%>
          <% end %>
            <br>
            <h5 style="text-decoration: underline;">Previous Bids</h5>
            <% @auction.bids.each do |bid| %>
              <%= bid.bid %>
                <hr>
                <% end %>
  </div>

  <!-- Tried to follow awesome answers class project to get some 
    help but not sure why bidding isn't displaying. Looked into it for a few hours still unsure -->


  <div class="other-show-div">
    <p>Current Price: </p>
    <p>Ends at: <b><%= @auction.ends_at %></b></p>
    <p>Reserve Price: </p>
  </div>
</div>

biddr_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiddrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="navbar-div">

     <a href="http://www.localhost:3000/" class="logo"><%= image_tag('biddr.jpg', width: '100px' , height: '40px') %></a>

      <div class="home-auctions-div">
        <span style="margin-right: 20px;">
        <%= link_to "Home", root_path, :class => "btn btn-dark" %>
      </span>
          <%= link_to "Auctions" , auctions_path, :class => "btn btn-dark" %>
      </div>

    <% if user_signed_in? %>
    <div style="margin: 7px 3px 0px 0px;">
      Hello <%= current_user.first_name %>,
    </div>
        <%= link_to "Logout" , sessions_path,  method: :delete, data: {confirm: "are you sure you want to log out?" }, :class => "btn btn-dark"%>
          <% else %>
          <div style="margin-right: 20px;">
            <%= link_to "Login" , new_sessions_path, :class => "btn btn-dark" %>
          </div>
              <%= link_to "Sign Up" , new_user_path, :class => "btn btn-dark" %>
                <% end %>
              </div>
                  

    <%= yield %>
  </body>
</html>

biddr_api/app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1 style="text-align: center;">Sign Up</h1>

<div class="signup-div">
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div class="signup">
    <%= f.label :first_name %> <br>
    <%= f.text_field :first_name %> <br> <br>
  
    <%= f.label :last_name %> <br>
    <%= f.text_field :last_name %> <br> <br>
  
    <%= f.label :email %> <br>
    <%= f.email_field :email %> <br> <br>
  
    <%= f.label :password %> <br> 
    <%= f.password_field :password %> <br> <br>
  
    <%= f.label :password_confirmation %> <br>
    <%= f.password_field :password_confirmation %> <br> <br>
    <%= f.submit "Sign Up", :class => "btn btn-secondary" %>
  </div>
<% end %>
</div>